### ISSUE TITLE
Python 3.5 incorrectly reported as unsupported

### ISSUE THREAD

**Issue by eddloschi** [PySide/pyside-setup#58]
Version 1.2.4, specifically commit 01cefeaaed9632d7ddc0c12568b9e68a20157f4b, introduced python version check, but a couple of days ago I successfully installed PySide 1.2.3 on my python 3.5 virtualenv.

So I suggest adding python 3.5 to the supported versions.

**Comment by ctismer** [comment]
Invalid request, because there was no info about the platform...

If you can provide a patch that works on Windows, Mac OS X 10.11 and Linux, including all
testing with and without virtualenv, then pls. submit a PR. Otherwise, don't!

If you have a version that works on XY, but not on Windows with the new MSVC
compiler, then forget it, or invent a better way to diversify our check for a valid python version.

We don't need something that sometimes works, but we need a thing that always works.
Please consider _why_ we introduced that check -- any idea?
